# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
darkmode: true

# Personal info
name: Stephanus Nugraha
title: DevOps Engineer
email: gmail@stephanusnugraha.com
#website: stephanusnugraha.com

# Social links
#twitter_username: -
github_username:  stephanusn
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: -
linkedin_username: stephanusnugraha
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I love automation and integrate them with modern technology. I create yaml, bash, or also python to make it all automate. 
  DevOps engineering is a never-ending puzzle that I am passionately engaged in solving. I have been obsessed with the idea of using automation pipeline to make developer life more fun and easier :)

  I enjoy: Kubernetes, GCP, AWS, Ansible, Terraform, Vault, Jenkins, Istio and some application to make the great pipeline.

  Versioning tools: Git, GitHub, Bitbucket.

  Security tools: Sonarqube, Nexus, DependencyCheck, OwaspZAP, Trivy.

  Observability tools: Prometheus - Grafana and ElasticStack

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
educaton_title: Certification

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in DevOps and Cloud Native some of my other interests and hobbies are:
   - Spend time with my family :)
   - Watching (not doing) Football and Dota2
   - Read, read and read

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
