# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
darkmode: true

# Personal info
name: Stephanus Nugraha
title: DevOps Engineer
email: gmail@stephanusnugraha.com
website: stephanusnugraha.com

# Social links
#twitter_username: -
github_username:  stephanusn
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: -
linkedin_username: stephanusnugraha
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I love automation and integrate them with modern technology. I create yaml, bash, or also python to make it all automate. 
  DevOps engineering is a never-ending puzzle that I am passionately engaged in solving. I have been obsessed with the idea of using automation pipeline to make developer life more fun and easier :)

  I enjoy with Kubernetes, GCP, AWS, Ansible, Terraform, Vault, Jenkins, Istio and some application to make the great pipeline.
  Versioning tools like Git, GitHub, Bitbucket.
  Security tools like Sonarqube, Nexus, DependencyCheck, OwaspZAP, Trivy.
  Observability tools like Prometheus - Grafana and ElasticStack

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
