# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
darkmode: true

# Personal info
name: Stephanus Nugraha
title: DevOps Engineer
email: gmail@stephanusnugraha.com
#website: stephanusnugraha.com

# Social links
#twitter_username: -
github_username:  stephanusn
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: -
linkedin_username: stephanusnugraha-537581102
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I love automation and integrate them with modern technology. Create a YAML file, bash, or python script to make it all automated.
  
  DevOps engineering is a never-ending puzzle that I am passionately engaged in solving. I have been obsessed with the idea of using automation pipeline to make developer more fun and easier :)

  Interest with Kubernetes, Helm, Ansible, Terraform, Jenkins, and some applications to make a great pipeline

  Cloud: GCP, AWS

  Mesh: Istio

  Versioning tools: Git, GitHub, Bitbucket

  Secret tools: Vault Hashicorp

  Security tools: Sonarqube, Nexus, DependencyCheck, OwaspZAP

  Observability tools: Prometheus-Grafana, ElasticStack

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Certification

# More Section
more_title: Certification
more_content: | # this will include new lines to allow paragraphs
  I have some certificate:
   - Certification Kubernetes Administration
   - Certification Kubernetes Developer Application

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
